### ISSUE TITLE
How to get MRMR into a cross-validation pipeline?

### ISSUE THREAD

**Issue by notuntoward** [ThomasBury/arfs#17]
I'd like to get `arfs.feature_selection.MinRedundancyMaxRelevance` into a cross-validation pipeline which tunes `n_features_to_select`.  In other words, I'd like to do something like is done in this example for PCA:

```
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=0)

pipe = Pipeline([('pca', PCA()), ('svc', SVC())])

param_grid = {
    'pca__n_components': [2, 5, 10],
    'svc__C': [0.1, 1, 10],
    'svc__kernel': ['linear', 'rbf']
}

grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train, y_train)

print("Best parameter (CV score=%0.3f):" % grid.best_score_)
print(grid.best_params_)
```

The problem is that the MinRedundancyMaxRelevance() class constructor requires that `n_features_to_select` be specified at initialization; I can't instantiate with no arguments, like with `PCA()` above, and that means, as far as I can tell, that I can't tune `n_features_to_select` within a pipeline.

But am I missing something?  Is there a different way to tune `n_features_to_select` within a pipeline?

**Comment by ThomasBury** [comment]
Dear @notuntoward, thanks for bringing up this issue. Unlike sklearn's `PCA`, I did not set a default value for `n_features_to_select` in the `MinRedundancyMaxRelevance` class. In `PCA`, the default is `n_components=None`, which means `n_components` is set to `min(n_samples, n_features) - 1` when the class is instantiated. However, in my package, this argument needs to be provided explicitly, but don't worry, you can still tune it.

To address the error message you see with `GridSearchCV`, you can simply tune the `n_features_to_select` parameter by setting it to the number of features in your training set: `MinRedundancyMaxRelevance(n_features_to_select=X_train.shape[1])`  This will prevent the error message from popping up, and you can then run your pipeline as usual. Behind the scene, `GridSearchCV ` changes the attribute(s) and re-runs the fit method.

Let me know if that works.

**Comment by ThomasBury** [comment]
Hello @notuntoward, I have made changes to the example you provided (please update to version `1.0.6`), the iris data set has only 4 predictors. Running grid-search (with cross-validation) + MRmr might be time-consuming. 

```python
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from arfs.utils import load_data
from arfs.feature_selection import MinRedundancyMaxRelevance
from sklearn.model_selection import train_test_split
from lightgbm import LGBMRegressor

boston = load_data(name="Boston")
X, y = boston.data, boston.target
y.name = "target"
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# To instantiate the class, a value for n_features_to_select must be provided, as no default value is available. This value will 
# be updated with one of the values in the grid.
pipe = Pipeline([('mrmr', MinRedundancyMaxRelevance(n_features_to_select=2)), ('gbm', LGBMRegressor())])

param_grid = {
    'mrmr__n_features_to_select': [2, 5, 7],
}

grid = GridSearchCV(pipe, param_grid=param_grid)
grid.fit(X_train, y_train)

print("Best parameter (CV score=%0.3f):" % grid.best_score_)
print(grid.best_params_)
```

**Comment by ThomasBury** [comment]
Dear @notuntoward,

Here are some suggestions that might help:

1. The warning message might occur due to a division by zero while computing quantities such as conditional entropy (Theyl's U statistics). To prevent this, I have already patched the code to handle zero division in the conditional entropy calculation. However, it is still important to check the data quality and ensure that there are no levels with zero occurrences. If such levels exist, you can remove them from the categorical column.
2. The warning message suggests that two columns have been removed because they contained only a single value (e.g., ["a", "a", "a", "a", ..., "a"]). Such columns do not provide useful information and can lead to errors in computation. To remove such "zero variance" columns, you can use the UniqueValuesThreshold transformer provided in the ARFS package.
3. Currently, there is no option to change the naming convention. However, the naming is standardized internally for implementation convenience.

Here is a working example of what you're trying to achieve. Please note that MRmr is known to be computationally intensive, so incorporating it into a grid search may be slow due to the significant number of necessary iterations.

```python
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from arfs.utils import load_data
from arfs.feature_selection import MinRedundancyMaxRelevance
from sklearn.model_selection import train_test_split
from lightgbm import LGBMRegressor

boston = load_data(name="Boston")
X, y = boston.data, boston.target
y.name = "target"
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# To instantiate the class, a value for n_features_to_select must be provided, as no default value is available. This value will 
# be updated with one of the values in the grid.
pipe = Pipeline([('mrmr', MinRedundancyMaxRelevance(n_features_to_select=5, show_progress=False)), ('gbm', LGBMRegressor())])

# pipe.fit(X_train, y_train)

param_grid = {
    'mrmr__n_features_to_select': [4, 5],
}

grid = GridSearchCV(pipe, param_grid=param_grid, cv=2)
grid.fit(X_train, y_train)

print("Best parameter (CV score=%0.3f):" % grid.best_score_)
print(grid.best_params_)
```

The output should be 

```
Best parameter (CV score=0.824):
{'mrmr__n_features_to_select': 5}
```
